name: 'Test job'
on:
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    name: Test job to run the custom action
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update locales
        uses: ./
        with:
          tolgee_secret: ${{ secrets.TOLGEE_API_KEY }}
          author_name: 'Larsluph'
          author_email: 'larsluph@gmail.com'
          commit_message: 'chore(localization): Update locales'
